const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  black: '#000',
  red: '#FF0000',
  gray: '#50515F',
  default: '#FCD501',
  default2: '#0086FD',
  green_gradiente: '#6CCFA4',
  green_light: '#DFFFF1',
  drawer: '#F1F1F1',
  gray_tab: '#748c94',
  white: '#fff',
  text_selected: '#333333',
  text_error: '#eb4a46',
  background: '#f6f6f6',
  buttonRed: '#B5151C',
  background_button: '#C7E7D9',
  background_types: '#F08474',
  border_color: '#c2c2c2',
  primary: '#4CAF50',
  secondary: '#FF5722',
  userMessage: '#E3F2FD',
  botMessage: '#FFFFFF',
};
